import type { ThemeDefinition } from 'vuetify'

// Signal Dashboard inspired palette
// Primary: Matrix Green (#22C55E)
// Sidebar: Deep green-black (#090e0c)
// Background: Mint-tinted light (#F3F8F5) / Dark: (#0F1512)

export const staticPrimaryColor = '#22C55E'
export const staticPrimaryDarkenColor = '#16A34A'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#64748B',
      'on-secondary': '#fff',
      'secondary-darken-1': '#475569',
      'success': '#22C55E',
      'on-success': '#fff',
      'success-darken-1': '#16A34A',
      'info': '#06B6D4',
      'on-info': '#fff',
      'info-darken-1': '#0891B2',
      'warning': '#F59E0B',
      'on-warning': '#fff',
      'warning-darken-1': '#D97706',
      'error': '#EF4444',
      'on-error': '#fff',
      'error-darken-1': '#DC2626',
      'background': '#F3F8F5',
      'on-background': '#1A1F1C',
      'surface': '#FFFFFF',
      'on-surface': '#1A1F1C',
      'grey-50': '#F9FAFB',
      'grey-100': '#F3F4F6',
      'grey-200': '#E5E7EB',
      'grey-300': '#D1D5DB',
      'grey-400': '#9CA3AF',
      'grey-500': '#6B7280',
      'grey-600': '#4B5563',
      'grey-700': '#374151',
      'grey-800': '#1F2937',
      'grey-900': '#111827',
      'grey-light': '#F9FAFB',
      'perfect-scrollbar-thumb': '#D1D5DB',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#F9FAFB',
      'sidebar-bg': '#090E0C',
      'sidebar-text': '#A7C3B2',
    },

    variables: {
      'code-color': '#22C55E',
      'overlay-scrim-background': '#1A1F1C',
      'tooltip-background': '#1A1F1C',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.05,
      'focus-opacity': 0.08,
      'selected-opacity': 0.08,
      'activated-opacity': 0.14,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'disabled-opacity': 0.38,
      'border-color': '#1A1F1C',
      'border-opacity': 0.1,
      'table-header-color': '#E8F5EE',
      'high-emphasis-opacity': 0.92,
      'medium-emphasis-opacity': 0.68,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#E5E7EB',

      // Shadows — very subtle for flat look
      'shadow-key-umbra-color': '#1A1F1C',
      'shadow-xs-opacity': 0.06,
      'shadow-sm-opacity': 0.08,
      'shadow-md-opacity': 0.10,
      'shadow-lg-opacity': 0.12,
      'shadow-xl-opacity': 0.14,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#64748B',
      'on-secondary': '#fff',
      'secondary-darken-1': '#475569',
      'success': '#22C55E',
      'on-success': '#fff',
      'success-darken-1': '#16A34A',
      'info': '#06B6D4',
      'on-info': '#fff',
      'info-darken-1': '#0891B2',
      'warning': '#F59E0B',
      'on-warning': '#fff',
      'warning-darken-1': '#D97706',
      'error': '#EF4444',
      'on-error': '#fff',
      'error-darken-1': '#DC2626',
      'background': '#0F1512',
      'on-background': '#E2EDE7',
      'surface': '#172118',
      'on-surface': '#E2EDE7',
      'grey-50': '#1A2A1F',
      'grey-100': '#1F2F24',
      'grey-200': '#1A2A1F',
      'grey-300': '#2D4036',
      'grey-400': '#3D5448',
      'grey-500': '#5A7A68',
      'grey-600': '#7CA88E',
      'grey-700': '#9AC0AA',
      'grey-800': '#C0D9C9',
      'grey-900': '#E2EDE7',
      'grey-light': '#1F2F24',
      'perfect-scrollbar-thumb': '#2D4036',
      'skin-bordered-background': '#172118',
      'skin-bordered-surface': '#172118',
      'sidebar-bg': '#090E0C',
      'sidebar-text': '#7CA88E',
    },
    variables: {
      'code-color': '#22C55E',
      'overlay-scrim-background': '#060A07',
      'tooltip-background': '#E2EDE7',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.38,
      'border-color': '#E2EDE7',
      'border-opacity': 0.10,
      'table-header-color': '#1F2F24',
      'high-emphasis-opacity': 0.92,
      'medium-emphasis-opacity': 0.68,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#2D4036',

      // Shadows
      'shadow-key-umbra-color': '#050905',
      'shadow-xs-opacity': 0.18,
      'shadow-sm-opacity': 0.22,
      'shadow-md-opacity': 0.26,
      'shadow-lg-opacity': 0.30,
      'shadow-xl-opacity': 0.34,
    },
  },
}

export default themes
