<?php

namespace Tests\Feature;

use App\Models\AuditLog;
use App\Models\Permission;
use App\Models\Role;
use App\Models\School;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class PhaseFiveSaasAdminApiTest extends TestCase
{
    use RefreshDatabase;

    public function test_super_admin_middleware_blocks_non_super_admin_users(): void
    {
        $user = User::factory()->create();

        Sanctum::actingAs($user);

        $this->getJson('/api/admin/system/stats')->assertForbidden();
    }

    public function test_super_admin_can_manage_school_saas_profile_and_onboarding(): void
    {
        $this->seed();
        $admin = User::factory()->create();
        $school = School::query()->create(['name' => 'Administered School', 'slug' => 'administered-school']);
        $this->grantSystemRole($admin, $school, 'super-admin');

        Sanctum::actingAs($admin);

        $this->getJson('/api/admin/system/stats')
            ->assertOk()
            ->assertJsonPath('data.schools', 1);

        $this->patchJson("/api/admin/schools/{$school->id}", [
            'plan' => 'growth',
            'subscription_status' => 'active',
            'plan_limits' => [
                'max_students' => 500,
                'max_employees' => 75,
                'max_storage_mb' => 2048,
                'reports_enabled' => true,
                'api_access' => true,
            ],
        ])
            ->assertOk()
            ->assertJsonPath('data.plan', 'growth')
            ->assertJsonPath('data.plan_limits.max_students', 500);

        $this->postJson("/api/admin/schools/{$school->id}/onboard")
            ->assertOk()
            ->assertJsonPath('data.subscription_status', 'trialing');

        $this->assertDatabaseHas('audit_logs', [
            'school_id' => $school->id,
            'actor_id' => $admin->id,
            'event' => 'school.onboarded',
        ]);
        $this->assertDatabaseHas('roles', [
            'school_id' => $school->id,
            'key' => 'school-admin',
            'is_system' => true,
        ]);
    }

    public function test_school_settings_endpoint_uses_typed_phase_five_shape(): void
    {
        $user = User::factory()->create();
        $school = School::query()->create(['name' => 'Settings School', 'slug' => 'settings-school']);
        $this->addActiveMember($user, $school);
        $this->grantSchoolPermission($user, $school, 'schools.manage', 'schools');

        Sanctum::actingAs($user);

        $this->patchJson("/api/schools/{$school->id}/settings", [
            'timezone' => 'Asia/Dhaka',
            'locale' => 'en_BD',
            'currency' => 'BDT',
            'academic_year_start_month' => 1,
            'date_format' => 'd/m/Y',
            'sms_enabled' => true,
            'sms_provider' => 'mock-sms',
            'sms_api_key' => 'secret',
            'attendance_warning_threshold_percent' => 80,
            'fee_invoice_prefix' => 'FEE',
            'allow_parent_portal' => true,
            'allow_student_portal' => true,
            'pdf_footer_text' => 'Generated by School SaaS',
        ])
            ->assertOk()
            ->assertJsonPath('data.timezone', 'Asia/Dhaka')
            ->assertJsonPath('data.currency', 'BDT')
            ->assertJsonPath('data.allow_parent_portal', true);

        $this->getJson("/api/schools/{$school->id}/settings")
            ->assertOk()
            ->assertJsonPath('data.fee_invoice_prefix', 'FEE');

        $this->assertDatabaseHas('audit_logs', [
            'school_id' => $school->id,
            'actor_id' => $user->id,
            'event' => 'school.settings.updated',
        ]);
    }

    public function test_plan_limit_returns_422_when_student_limit_is_reached(): void
    {
        $user = User::factory()->create();
        $school = School::query()->create([
            'name' => 'Limit School',
            'slug' => 'limit-school',
            'plan_limits' => ['max_students' => 1],
        ]);
        $this->addActiveMember($user, $school);
        $this->grantSchoolPermission($user, $school, 'students.manage', 'people');
        $school->students()->create([
            'admission_no' => 'ADM-LIMIT-01',
            'full_name' => 'Existing Student',
            'admitted_on' => '2026-01-01',
        ]);

        Sanctum::actingAs($user);

        $this->postJson("/api/schools/{$school->id}/students", [
            'admission_no' => 'ADM-LIMIT-02',
            'full_name' => 'Blocked Student',
            'admitted_on' => '2026-01-02',
        ])
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['student', 'error']);
    }

    public function test_school_audit_viewer_is_paginated_and_school_scoped(): void
    {
        $user = User::factory()->create();
        $school = School::query()->create(['name' => 'Audit School', 'slug' => 'audit-school']);
        $otherSchool = School::query()->create(['name' => 'Other Audit School', 'slug' => 'other-audit-school']);
        $this->addActiveMember($user, $school);
        $this->grantSchoolPermission($user, $school, 'audit.view', 'audit');

        AuditLog::query()->create(['school_id' => $school->id, 'actor_id' => $user->id, 'event' => 'school.updated']);
        AuditLog::query()->create(['school_id' => $otherSchool->id, 'actor_id' => $user->id, 'event' => 'school.updated']);

        Sanctum::actingAs($user);

        $this->getJson("/api/schools/{$school->id}/audit-logs?event=school.updated&per_page=1")
            ->assertOk()
            ->assertJsonPath('data.0.school_id', $school->id)
            ->assertJsonPath('meta.total', 1);
    }

    private function addActiveMember(User $user, School $school): void
    {
        $school->memberships()->create([
            'user_id' => $user->id,
            'status' => 'active',
            'joined_at' => now(),
        ]);
    }

    private function grantSystemRole(User $user, School $school, string $roleKey): void
    {
        $role = Role::query()
            ->whereNull('school_id')
            ->where('key', $roleKey)
            ->firstOrFail();

        $user->roleAssignments()->create([
            'school_id' => $school->id,
            'role_id' => $role->id,
        ]);
    }

    private function grantSchoolPermission(User $user, School $school, string $permissionKey, string $module): void
    {
        $permission = Permission::query()->firstOrCreate(
            ['key' => $permissionKey],
            [
                'module' => $module,
                'description' => str($permissionKey)->replace('.', ' ')->headline()->toString(),
            ]
        );

        $role = Role::query()->create([
            'school_id' => $school->id,
            'name' => str($permissionKey)->replace('.', ' ')->headline()->append(' Manager')->toString(),
            'key' => str($permissionKey)->slug()->append('-manager')->toString(),
        ]);

        $role->permissions()->attach($permission);

        $user->roleAssignments()->create([
            'school_id' => $school->id,
            'role_id' => $role->id,
        ]);
    }
}
