<?php

namespace Tests\Feature;

use App\Models\AuditLog;
use App\Models\Permission;
use App\Models\Role;
use App\Models\School;
use App\Models\SchoolInvitation;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class PhaseFiveSaasAdminApiTest extends TestCase
{
    use RefreshDatabase;

    public function test_super_admin_middleware_blocks_non_super_admin_users(): void
    {
        $user = User::factory()->create();

        Sanctum::actingAs($user);

        $this->getJson('/api/admin/system/stats')->assertForbidden();
    }

    public function test_super_admin_can_manage_school_saas_profile_and_onboarding(): void
    {
        $this->seed();
        $admin = User::factory()->create();
        $school = School::query()->create(['name' => 'Administered School', 'slug' => 'administered-school']);
        $this->grantSystemRole($admin, $school, 'super-admin');

        Sanctum::actingAs($admin);

        $this->getJson('/api/admin/system/stats')
            ->assertOk()
            ->assertJsonPath('data.schools', 1);

        $this->patchJson("/api/admin/schools/{$school->id}", [
            'plan' => 'growth',
            'subscription_status' => 'active',
            'plan_limits' => [
                'max_students' => 500,
                'max_employees' => 75,
                'max_storage_mb' => 2048,
                'reports_enabled' => true,
                'api_access' => true,
            ],
        ])
            ->assertOk()
            ->assertJsonPath('data.plan', 'growth')
            ->assertJsonPath('data.plan_limits.max_students', 500);

        $this->postJson("/api/admin/schools/{$school->id}/onboard")
            ->assertOk()
            ->assertJsonPath('data.subscription_status', 'trialing');

        $this->assertDatabaseHas('audit_logs', [
            'school_id' => $school->id,
            'actor_id' => $admin->id,
            'event' => 'school.onboarded',
        ]);
        $this->assertDatabaseHas('roles', [
            'school_id' => $school->id,
            'key' => 'school-admin',
            'is_system' => true,
        ]);
    }

    public function test_school_settings_endpoint_uses_typed_phase_five_shape(): void
    {
        $user = User::factory()->create();
        $school = School::query()->create(['name' => 'Settings School', 'slug' => 'settings-school']);
        $this->addActiveMember($user, $school);
        $this->grantSchoolPermission($user, $school, 'schools.manage', 'schools');

        Sanctum::actingAs($user);

        $this->patchJson("/api/schools/{$school->id}/settings", [
            'timezone' => 'Asia/Dhaka',
            'locale' => 'en_BD',
            'currency' => 'BDT',
            'academic_year_start_month' => 1,
            'date_format' => 'd/m/Y',
            'sms_enabled' => true,
            'sms_provider' => 'mock-sms',
            'sms_api_key' => 'secret',
            'attendance_warning_threshold_percent' => 80,
            'fee_invoice_prefix' => 'FEE',
            'allow_parent_portal' => true,
            'allow_student_portal' => true,
            'pdf_footer_text' => 'Generated by School SaaS',
        ])
            ->assertOk()
            ->assertJsonPath('data.timezone', 'Asia/Dhaka')
            ->assertJsonPath('data.currency', 'BDT')
            ->assertJsonPath('data.allow_parent_portal', true);

        $this->getJson("/api/schools/{$school->id}/settings")
            ->assertOk()
            ->assertJsonPath('data.fee_invoice_prefix', 'FEE');

        $this->assertDatabaseHas('audit_logs', [
            'school_id' => $school->id,
            'actor_id' => $user->id,
            'event' => 'school.settings.updated',
        ]);
    }

    public function test_plan_limit_returns_422_when_student_limit_is_reached(): void
    {
        $user = User::factory()->create();
        $school = School::query()->create([
            'name' => 'Limit School',
            'slug' => 'limit-school',
            'plan_limits' => ['max_students' => 1],
        ]);
        $this->addActiveMember($user, $school);
        $this->grantSchoolPermission($user, $school, 'students.manage', 'people');
        $school->students()->create([
            'admission_no' => 'ADM-LIMIT-01',
            'full_name' => 'Existing Student',
            'admitted_on' => '2026-01-01',
        ]);

        Sanctum::actingAs($user);

        $this->postJson("/api/schools/{$school->id}/students", [
            'admission_no' => 'ADM-LIMIT-02',
            'full_name' => 'Blocked Student',
            'admitted_on' => '2026-01-02',
        ])
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['student', 'error']);
    }

    public function test_school_audit_viewer_is_paginated_and_school_scoped(): void
    {
        $user = User::factory()->create();
        $school = School::query()->create(['name' => 'Audit School', 'slug' => 'audit-school']);
        $otherSchool = School::query()->create(['name' => 'Other Audit School', 'slug' => 'other-audit-school']);
        $this->addActiveMember($user, $school);
        $this->grantSchoolPermission($user, $school, 'audit.view', 'audit');

        AuditLog::query()->create(['school_id' => $school->id, 'actor_id' => $user->id, 'event' => 'school.updated']);
        AuditLog::query()->create(['school_id' => $otherSchool->id, 'actor_id' => $user->id, 'event' => 'school.updated']);

        Sanctum::actingAs($user);

        $this->getJson("/api/schools/{$school->id}/audit-logs?event=school.updated&per_page=1")
            ->assertOk()
            ->assertJsonPath('data.0.school_id', $school->id)
            ->assertJsonPath('meta.total', 1);
    }

    public function test_school_user_manager_can_create_list_revoke_and_accept_invitation_tokens(): void
    {
        $manager = User::factory()->create();
        $invitee = User::factory()->create(['email' => 'new.teacher@example.test']);
        $school = School::query()->create(['name' => 'Invite School', 'slug' => 'invite-school']);
        $this->addActiveMember($manager, $school);
        $this->grantSchoolPermission($manager, $school, 'users.manage', 'users');
        $teacherRole = Role::query()->create([
            'school_id' => $school->id,
            'name' => 'Teacher',
            'key' => 'teacher',
            'is_system' => true,
        ]);

        Sanctum::actingAs($manager);

        $token = $this->postJson("/api/schools/{$school->id}/invitations", [
            'email' => 'New.Teacher@example.test',
            'name' => 'New Teacher',
            'role_id' => $teacherRole->id,
        ])
            ->assertCreated()
            ->assertJsonPath('data.email', 'new.teacher@example.test')
            ->assertJsonPath('data.role.key', 'teacher')
            ->json('data.token');

        $this->getJson("/api/schools/{$school->id}/invitations")
            ->assertOk()
            ->assertJsonPath('data.0.email', 'new.teacher@example.test');

        Sanctum::actingAs($invitee);

        $this->postJson("/api/invitations/{$token}/accept")
            ->assertOk()
            ->assertJsonPath('data.status', 'accepted')
            ->assertJsonPath('data.school.id', $school->id);

        $this->assertDatabaseHas('school_memberships', [
            'school_id' => $school->id,
            'user_id' => $invitee->id,
            'status' => 'active',
        ]);
        $this->assertDatabaseHas('user_role_assignments', [
            'school_id' => $school->id,
            'user_id' => $invitee->id,
            'role_id' => $teacherRole->id,
        ]);

        Sanctum::actingAs($manager);
        $revokedInvitationId = $this->postJson("/api/schools/{$school->id}/invitations", [
            'email' => 'revoked@example.test',
        ])->assertCreated()->json('data.id');

        $this->deleteJson("/api/schools/{$school->id}/invitations/{$revokedInvitationId}")
            ->assertNoContent();

        $this->assertDatabaseHas('school_invitations', [
            'id' => $revokedInvitationId,
            'status' => 'revoked',
        ]);
    }

    public function test_invitation_accept_rejects_expired_tokens(): void
    {
        $invitee = User::factory()->create(['email' => 'expired.invitee@example.test']);
        $school = School::query()->create(['name' => 'Expired Invite School', 'slug' => 'expired-invite-school']);
        $invitation = SchoolInvitation::query()->create([
            'school_id' => $school->id,
            'email' => $invitee->email,
            'token' => '11111111-1111-4111-8111-111111111111',
            'status' => 'pending',
            'expires_at' => now()->subMinute(),
        ]);

        Sanctum::actingAs($invitee);

        $this->postJson("/api/invitations/{$invitation->token}/accept")
            ->assertUnprocessable()
            ->assertJsonValidationErrors('token');

        $this->assertDatabaseHas('school_invitations', [
            'id' => $invitation->id,
            'status' => 'expired',
        ]);
    }

    public function test_student_portal_endpoints_return_only_authenticated_student_records(): void
    {
        $studentUser = User::factory()->create(['email' => 'student.portal@example.test']);
        $school = School::query()->create(['name' => 'Student Portal School', 'slug' => 'student-portal-school']);
        $this->addActiveMember($studentUser, $school);
        $this->grantSchoolPermission($studentUser, $school, 'student.portal.view', 'portal');
        $records = $this->createPortalRecords($school, 'student.portal@example.test', 'guardian.portal@example.test', $studentUser);

        Sanctum::actingAs($studentUser);

        $this->getJson("/api/schools/{$school->id}/portal/student/profile")
            ->assertOk()
            ->assertJsonPath('data.email', 'student.portal@example.test')
            ->assertJsonPath('data.enrollments.0.id', $records['enrollment']->id);

        $this->getJson("/api/schools/{$school->id}/portal/student/attendance")
            ->assertOk()
            ->assertJsonPath('data.0.status', 'present');

        $this->getJson("/api/schools/{$school->id}/portal/student/results")
            ->assertOk()
            ->assertJsonPath('data.0.grade', 'A+');

        $this->getJson("/api/schools/{$school->id}/portal/student/invoices")
            ->assertOk()
            ->assertJsonPath('data.0.invoice_no', 'INV-PORTAL-01');

        $this->getJson("/api/schools/{$school->id}/portal/student/notifications")
            ->assertOk()
            ->assertJsonPath('data.0.type', 'portal.notice');
    }

    public function test_parent_portal_endpoints_return_linked_children_records(): void
    {
        $parentUser = User::factory()->create(['email' => 'parent.portal@example.test']);
        $school = School::query()->create(['name' => 'Parent Portal School', 'slug' => 'parent-portal-school']);
        $this->addActiveMember($parentUser, $school);
        $this->grantSchoolPermission($parentUser, $school, 'parent.portal.view', 'portal');
        $records = $this->createPortalRecords($school, 'child.portal@example.test', 'parent.portal@example.test', $parentUser);
        $enrollmentId = $records['enrollment']->id;

        Sanctum::actingAs($parentUser);

        $this->getJson("/api/schools/{$school->id}/portal/parent/children")
            ->assertOk()
            ->assertJsonPath('data.0.email', 'child.portal@example.test')
            ->assertJsonPath('data.0.enrollments.0.id', $enrollmentId);

        $this->getJson("/api/schools/{$school->id}/portal/parent/children/{$enrollmentId}/attendance")
            ->assertOk()
            ->assertJsonPath('data.0.status', 'present');

        $this->getJson("/api/schools/{$school->id}/portal/parent/children/{$enrollmentId}/results")
            ->assertOk()
            ->assertJsonPath('data.0.grade', 'A+');

        $this->getJson("/api/schools/{$school->id}/portal/parent/children/{$enrollmentId}/invoices")
            ->assertOk()
            ->assertJsonPath('data.0.invoice_no', 'INV-PORTAL-01');

        $this->getJson("/api/schools/{$school->id}/portal/parent/notifications")
            ->assertOk()
            ->assertJsonPath('data.0.type', 'portal.notice');
    }

    private function addActiveMember(User $user, School $school): void
    {
        $school->memberships()->create([
            'user_id' => $user->id,
            'status' => 'active',
            'joined_at' => now(),
        ]);
    }

    private function grantSystemRole(User $user, School $school, string $roleKey): void
    {
        $role = Role::query()
            ->whereNull('school_id')
            ->where('key', $roleKey)
            ->firstOrFail();

        $user->roleAssignments()->create([
            'school_id' => $school->id,
            'role_id' => $role->id,
        ]);
    }

    private function grantSchoolPermission(User $user, School $school, string $permissionKey, string $module): void
    {
        $permission = Permission::query()->firstOrCreate(
            ['key' => $permissionKey],
            [
                'module' => $module,
                'description' => str($permissionKey)->replace('.', ' ')->headline()->toString(),
            ]
        );

        $role = Role::query()->create([
            'school_id' => $school->id,
            'name' => str($permissionKey)->replace('.', ' ')->headline()->append(' Manager')->toString(),
            'key' => str($permissionKey)->slug()->append('-manager')->toString(),
        ]);

        $role->permissions()->attach($permission);

        $user->roleAssignments()->create([
            'school_id' => $school->id,
            'role_id' => $role->id,
        ]);
    }

    /**
     * @return array<string, mixed>
     */
    private function createPortalRecords(School $school, string $studentEmail, string $guardianEmail, User $notificationUser): array
    {
        $academicYear = $school->academicYears()->create([
            'name' => 'Academic Year 2026',
            'code' => 'AY-2026',
            'starts_on' => '2026-01-01',
            'ends_on' => '2026-12-31',
        ]);
        $academicClass = $school->academicClasses()->create(['name' => 'Class Four', 'code' => 'C4']);
        $guardian = $school->guardians()->create([
            'full_name' => 'Portal Guardian',
            'email' => $guardianEmail,
        ]);
        $student = $school->students()->create([
            'guardian_id' => $guardian->id,
            'admission_no' => 'ADM-PORTAL-01',
            'full_name' => 'Portal Student',
            'email' => $studentEmail,
            'admitted_on' => '2026-01-05',
        ]);
        $enrollment = $school->studentEnrollments()->create([
            'student_id' => $student->id,
            'academic_year_id' => $academicYear->id,
            'academic_class_id' => $academicClass->id,
            'roll_no' => '7',
            'enrolled_on' => '2026-01-10',
        ]);
        $examType = $school->examTypes()->create(['name' => 'Final', 'code' => 'FIN']);
        $exam = $school->exams()->create([
            'exam_type_id' => $examType->id,
            'academic_year_id' => $academicYear->id,
            'name' => 'Final 2026',
            'code' => 'FIN-2026',
            'starts_on' => '2026-11-01',
            'ends_on' => '2026-11-15',
            'is_published' => true,
        ]);

        $school->studentAttendanceRecords()->create([
            'student_enrollment_id' => $enrollment->id,
            'attendance_date' => '2026-04-19',
            'status' => 'present',
        ]);
        $school->resultSummaries()->create([
            'exam_id' => $exam->id,
            'student_enrollment_id' => $enrollment->id,
            'total_marks_obtained' => 95,
            'total_full_marks' => 100,
            'percentage' => 95,
            'gpa' => 5,
            'grade' => 'A+',
            'position_in_class' => 1,
            'is_pass' => true,
            'computed_at' => now(),
        ]);
        $school->studentInvoices()->create([
            'student_enrollment_id' => $enrollment->id,
            'academic_year_id' => $academicYear->id,
            'invoice_no' => 'INV-PORTAL-01',
            'subtotal' => 1000,
            'discount' => 0,
            'total' => 1000,
            'paid_amount' => 500,
            'status' => 'partial',
        ]);
        $school->notifications()->create([
            'recipient_user_id' => $notificationUser->id,
            'type' => 'portal.notice',
            'title' => 'Portal notice',
            'body' => 'A portal update is ready.',
        ]);

        return ['student' => $student, 'guardian' => $guardian, 'enrollment' => $enrollment];
    }
}
